"""initial

Revision ID: 1cdcde80196a
Revises: 
Create Date: 2026-08-22 17:50:15.850022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1cdcde80196a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('sites',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('lat', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('lon', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('site_type', sa.String(length=50), nullable=False),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_actions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('trigger', sa.String(length=255), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alerts_site_time', 'alerts', ['site_id', 'created_at'], unique=False)
    op.create_index('idx_alerts_unacked', 'alerts', ['site_id'], unique=False, postgresql_where=sa.text('acknowledged = false'))
    op.create_table('energy_consumption',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.String(length=100), nullable=True),
    sa.Column('kwh', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_energy_site_time', 'energy_consumption', ['site_id', 'recorded_at'], unique=False)
    op.create_table('temperature_readings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('temperature_c', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('humidity_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('heat_index_c', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('apparent_temp_c', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_temp_site_time', 'temperature_readings', ['site_id', sa.literal_column('recorded_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_temp_site_time', table_name='temperature_readings')
    op.drop_table('temperature_readings')
    op.drop_index('idx_energy_site_time', table_name='energy_consumption')
    op.drop_table('energy_consumption')
    op.drop_index('idx_alerts_unacked', table_name='alerts', postgresql_where=sa.text('acknowledged = false'))
    op.drop_index('idx_alerts_site_time', table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('agent_actions')
    op.drop_table('sites')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
