from typing import Generic, TypeVar
from pydantic import BaseModel, Field, ConfigDict

T = TypeVar("T")

class PaginatedResponse(BaseModel, Generic[T]):
    """Generic schema for paginated responses."""
    items: list[T] = Field(description="List of items for the current page")
    total: int = Field(description="Total number of items")
    page: int = Field(description="Current page number")
    size: int = Field(description="Number of items per page")
    pages: int = Field(description="Total number of pages")

    model_config = ConfigDict(from_attributes=True)

class ErrorDetail(BaseModel):
    """Schema for individual field validation errors."""
    loc: list[str | int] = Field(description="Location of the error (e.g., ['body', 'email'])")
    msg: str = Field(description="Error message")
    type: str = Field(description="Error type identifier")

class ErrorResponse(BaseModel):
    """Standardized error response following RFC 7807 (Problem Details for HTTP APIs)."""
    type: str = Field(description="URI reference that identifies the problem type", default="about:blank")
    title: str = Field(description="A short, human-readable summary of the problem type")
    status: int = Field(description="The HTTP status code generated by the origin server for this occurrence of the problem")
    detail: str = Field(description="A human-readable explanation specific to this occurrence of the problem")
    instance: str | None = Field(description="A URI reference that identifies the specific occurrence of the problem", default=None)
    errors: list[ErrorDetail] | None = Field(description="List of specific validation errors", default=None)
